services:
  openfoam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${MY_UID:-1000}
        - GROUP_ID=${MY_GID:-1000}
    volumes:
      - ./docker_root:/home/openfoam/project
    working_dir: /home/openfoam/project
    # Use interactive shell
    stdin_open: true
    tty: true

  cantera:
    build:
      context: .
      dockerfile: Dockerfile.cantera
    volumes:
      - ./docker_root:/root/project
    working_dir: /root/project
    stdin_open: true
    tty: true
