version: '3.8'

services:
  openfoam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    volumes:
      - ./docker_root:/home/openfoam/project
    working_dir: /home/openfoam/project
    # Use interactive shell
    stdin_open: true
    tty: true
