services:
  openfoam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${MY_UID:-1000}
        - GROUP_ID=${MY_GID:-1000}
    volumes:
      - ./docker_root:/home/openfoam/project
    working_dir: /home/openfoam/project
    # Use interactive shell
    stdin_open: true
    tty: true

  cantera:
      image: python:3.14-slim
      volumes:
        - ./docker_root:/home/openfoam/project
      working_dir: /home/openfoam/project
      command: /bin/bash -c "pip install cantera numpy && bash"
      stdin_open: true
      tty: true