FROM python:3.14-slim
USER root
WORKDIR /opt
RUN apt-get update && apt-get install -y wget unzip && \
	wget https://shepherd.caltech.edu/EDL/PublicResources/sdt/SDToolbox.zip && \
	unzip SDToolbox.zip && \
	rm *.zip && \
	rm -rf /var/lib/apt/lists/* && \
	pip install cantera matplotlib numpy scipy
ENV PYTHONPATH="${PYTHONPATH}:/opt/SDToolbox/Python3"
ENV CANTERA_DATA="${CANTERA_DATA}:/root/project/cantera/data"
WORKDIR /root
CMD ["/bin/bash"]	
